<?php


namespace app\api\controller;



use Firebase\JWT\JWT;

class Base extends Cross
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        //鉴权
        //获取token，判断token是否存在，是否能够解码token

        //1.获取头部token,判断token是否存在且不为空
        $header = request()->header();
        if(!isset($header['token']) || empty($header['token'])){
            return json(['code'=>0, 'msg'=>'token不存在'])->send();
        }

        //解码
        $jwt = new JWT();
        $info = $jwt::decode($header['token'],'api123456',['HS256']);
        $this->aid = $info->aid;
    }
}