<?php


namespace app\api\controller;


use think\Controller;

class Cross extends Controller
{
    //初始化方法，解决跨域问题
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin: *');
        header('Access-Control-Allow-Methods: POST, GET, PUT, OPTIONS, DELETE'); //支持的http 动作
        header('Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, token, Accept, x-access-sign, x-access-time');
        if (request()->isOptions()) {
            exit();
        }
    }
}































